[meta]
#插件名称,也作为目录名
name="Cubelet-dynamicconf"
#1表示周期插件,2表示常驻插件,3表示资源包
type=3
[resource]
#资源文件或目录在主机上的路径(绝对路径)
host_path="/usr/local/services/cubetoolbox/Cubelet/dynamicconf/conf.yaml"
#资源文件在压缩包内的路径(压缩包内相对路径)
src_path="conf.yaml"
#获取版本信息文件路径
version_file="version"
