[meta]
name="Cubelet"
#1表示周期插件，2表示常驻插件,3表示资源包
type=2

[plugin]
#插件的可执行文件的路径,如果写相对路径会以cubetoolbox的路径(/usr/local/services/cubetoolbox/${plugin_name}/)为根路径
entrypoint="bin/cubelet"
#获取版本信息命令
version_cmd="bin/cubelet -v"
#可选,程序启动命令,如果不填,默认为entrypoint的值
start_cmd="/usr/local/services/cubetoolbox/Cubelet/bin/cubelet -c /usr/local/services/cubetoolbox/Cubelet/config/config.toml --dynamic-conf-path /usr/local/services/cubetoolbox/Cubelet/dynamicconf/conf.yaml"
#可选,结束插件的可执行文件路径，如果选项未指定，框架将发送SIGKILL信号到插件启动时的进程PID。
stop_cmd=""
#可选 重启脚本
reload_cmd=""
#可选 检查插件运行状态，这个选项目前有三种形式：
#     如果值为 $pid : 检测拉起时进程的pid。不推荐使用。
#     如果值以@开头：以@以后的字符串作为进程名，检测进程名是否在系统中存在, 推荐使用。
#     如果不符合上面两种：选项指定的是检测脚本的路径, 脚本返回值为0表示正在运行，否则表示未运行。
#     若不设置，则不检测插件运行状态。
plugin_health_check="@cubelet"
is_fork=true
pid_file = "/run/cube-let.pid"
start_secs = 180
[mode]
#值为 yes 表示框架启动时启动此插件，值为 no 表示框架启动时不启动此插件
run_start="yes"
#可选 如果为周期插件 按照crontab表达式解析执行周期
cron_pattern=""

[cgroup]
