{{- if and .Values.controlPlane.enabled .Values.controlPlane.templateCenter.enabled }}
{{- $conf := tpl (.Files.Get "files/cube-templatecenter/conf.yaml") . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cube.templateCenterConfigSecretName" . }}
  labels:
    {{- include "cube.labels" . | nindent 4 }}
    app.kubernetes.io/component: templatecenter
type: Opaque
stringData:
  conf.yaml: |-
{{ $conf | nindent 4 }}
{{- end }}
